# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.11 Form Designer
# Date : 27/10/2019
# Time : 04:15:44

Load "stdlib.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new App {
		StyleFusion()
		new welcomeView { win.show() } 
		exec()
	}
}

class welcomeView from WindowsViewParent
	win = new MainWindow() { 
		move(20,0)
		resize(787,712)
		setWindowTitle("Form1")
		setstylesheet("background-color:#6effe7;") 
		Label1 = new label(win) {
			move(271,19)
			resize(231,63)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,18,-1,5,50,0,0,0,0,0,Regular")
			setfont(oFont)
			oFont.delete()
			setText("Welcome to Koko")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
		Button1 = new pushbutton(win) {
			move(19,98)
			resize(735,54)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,18,-1,5,50,0,0,0,0,0,Regular")
			setfont(oFont)
			oFont.delete()
			setText("Say Hello")
			setClickEvent(Method(:hello))
			setBtnImage(Button1,"")
			
		}
		Frame1 = new frame3(win) {
			move(19,180)
			resize(735,414)
			setstylesheet("color:black;background-color:#00007f;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setFrameStyle(QFrame_Plain | QFrame_WinPanel)
		}
		Label2 = new label(win) {
			move(62,215)
			resize(125,37)
			setstylesheet("color:#ffffff;background-color:#00007f;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,18,-1,5,50,0,0,0,0,0,Regular")
			setfont(oFont)
			oFont.delete()
			setText("Name")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
		LineEdit1 = new lineedit(win) {
			move(197,504)
			resize(511,43)
			setstylesheet("color:black;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,18,-1,5,50,0,0,0,0,0,Regular")
			setfont(oFont)
			oFont.delete()
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent("")
			setselectionChangedEvent("")
			settextEditedEvent("")
			
		}
		LineEdit6 = new lineedit(win) {
			move(197,431)
			resize(511,43)
			setstylesheet("color:black;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,18,-1,5,50,0,0,0,0,0,Regular")
			setfont(oFont)
			oFont.delete()
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent("")
			setselectionChangedEvent("")
			settextEditedEvent("")
			
		}
		Label7 = new label(win) {
			move(62,292)
			resize(125,34)
			setstylesheet("color:#ffffff;background-color:#00007f;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,18,-1,5,50,0,0,0,0,0,Regular")
			setfont(oFont)
			oFont.delete()
			setText("Address")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
		LineEdit8 = new lineedit(win) {
			move(197,358)
			resize(191,43)
			setstylesheet("color:black;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,18,-1,5,50,0,0,0,0,0,Regular")
			setfont(oFont)
			oFont.delete()
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent("")
			setselectionChangedEvent("")
			settextEditedEvent("")
			
		}
		Label9 = new label(win) {
			move(62,366)
			resize(125,34)
			setstylesheet("color:#ffffff;background-color:#00007f;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,18,-1,5,50,0,0,0,0,0,Regular")
			setfont(oFont)
			oFont.delete()
			setText("Phone")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
		LineEdit10 = new lineedit(win) {
			move(197,285)
			resize(191,43)
			setstylesheet("color:black;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,18,-1,5,50,0,0,0,0,0,Regular")
			setfont(oFont)
			oFont.delete()
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent("")
			setselectionChangedEvent("")
			settextEditedEvent("")
			
		}
		Label11 = new label(win) {
			move(62,440)
			resize(125,37)
			setstylesheet("color:#ffffff;background-color:#00007f;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,18,-1,5,50,0,0,0,0,0,Regular")
			setfont(oFont)
			oFont.delete()
			setText("Job")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
		LineEdit12 = new lineedit(win) {
			move(197,212)
			resize(511,43)
			setstylesheet("color:black;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,18,-1,5,50,0,0,0,0,0,Regular")
			setfont(oFont)
			oFont.delete()
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent("")
			setselectionChangedEvent("")
			settextEditedEvent("")
			
		}
		Label13 = new label(win) {
			move(62,517)
			resize(125,37)
			setstylesheet("color:#ffffff;background-color:#00007f;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,18,-1,5,50,0,0,0,0,0,Regular")
			setfont(oFont)
			oFont.delete()
			setText("Notes")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
	}

# End of the Generated Source Code File...