# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.8 Form Designer
# Date : 11/03/2018
# Time : 02:44:26

Load "stdlib.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new App {
		StyleFusion()
		new test1View { win.show() } 
		exec()
	}
}

class test1View from WindowsViewParent
	win = new MainWindow() { 
		move(23,93)
		resize(400,400)
		setWindowTitle("Form1")
		setstylesheet("background-color:#d9ff4f;") 
		Label1 = new label(win) {
			move(61,23)
			resize(267,70)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,36,-1,5,50,0,0,0,0,0")
			setfont(oFont)
			oFont.delete()
			setText("Welcome")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
		Button1 = new pushbutton(win) {
			move(10,145)
			resize(376,72)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,36,-1,5,50,0,0,0,0,0")
			setfont(oFont)
			oFont.delete()
			setText("Say Hello")
			setClickEvent(Method(:sayhello))
			setBtnImage(Button1,"")
			
		}
		Button2 = new pushbutton(win) {
			move(10,257)
			resize(376,71)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,36,-1,5,50,0,0,0,0,0")
			setfont(oFont)
			oFont.delete()
			setText("Say Welcome")
			setClickEvent(Method(:saywelcome))
			setBtnImage(Button2,"")
			
		}
	}

# End of the Generated Source Code File...