# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.10 Form Designer
# Date : 21/02/2019
# Time : 20:30:39

Load "stdlib.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new App {
		StyleFusion()
		new test2View { win.show() } 
		exec()
	}
}

class test2View from WindowsViewParent
	win = new MainWindow() { 
		move(26,62)
		resize(654,493)
		setWindowTitle("Form1")
		setstylesheet("background-color:#0e3c55;") 
		Button1 = new pushbutton(win) {
			move(201,202)
			resize(241,54)
			setstylesheet("color:black;background-color:#ffff58;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("MS Shell Dlg 2,14,-1,5,50,0,0,0,0,0")
			setfont(oFont)
			oFont.delete()
			setText("Change Window Title")
			setClickEvent(Method(:change))
			setBtnImage(Button1,"")
			
		}
	}

# End of the Generated Source Code File...