# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.10 Form Designer
# Date : 21/02/2019
# Time : 20:20:53

Load "stdlib.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new App {
		StyleFusion()
		new test2View { win.show() } 
		exec()
	}
}

class test2View from WindowsViewParent
	win = new MainWindow() { 
		move(100,100)
		resize(400,400)
		setWindowTitle("Form1")
		setstylesheet("background-color:;") 
	}

# End of the Generated Source Code File...