# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.15 Form Designer
# Date : 16/08/2021
# Time : 12:03:27

Load "stdlibcore.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new App {
		StyleFusion()
		new myfirstappView { win.show() } 
		exec()
	}
}

class myfirstappView from WindowsViewParent
	win = new MainWindow() { 
		move(20,20)
		resize(400,400)
		setWindowTitle("My First Application")
		setstylesheet("background-color:#d1ff7c;") 
		Button1 = new pushbutton(win) {
			move(139,163)
			resize(114,45)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Hello")
			setClickEvent(Method(:SayHello))
			setBtnImage(Button1,"")
			
		}
		Layout1 = new QVBoxLayout() {
			AddWidget(Button1)
			
		}

		oMWLayoutWidget = new qWidget() { setLayout(Layout1) }
		setCentralWidget(oMWLayoutWidget) 
	}

# End of the Generated Source Code File...