# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.8 Form Designer
# Date : 06/03/2018
# Time : 17:27:52

Load "stdlib.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new App {
		StyleFusion()
		new testfd2View { win.show() } 
		exec()
	}
}

class testfd2View from WindowsViewParent
	win = new MainWindow() { 
		move(100,100)
		resize(400,400)
		setWindowTitle("Just as test")
		setstylesheet("background-color:;") 
		Button1 = new pushbutton(win) {
			move(55,60)
			resize(214,68)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Welcome")
			setClickEvent(Method(:welcome))
			setBtnImage(Button1,"")
			
		}
	}

# End of the Generated Source Code File...