# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.10 Form Designer
# Date : 21/02/2019
# Time : 21:24:57

Load "stdlib.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new App {
		StyleFusion()
		new testView { win.show() } 
		exec()
	}
}

class testView from WindowsViewParent
	win = new MainWindow() { 
		move(20,20)
		resize(470,706)
		setWindowTitle("Two Windows")
		setstylesheet("background-color:#f4ff75;") 

		setWindowFlags(Qt_Window | Qt_WindowTitleHint | Qt_WindowCloseButtonHint | Qt_CustomizeWindowHint) 
		ListWidget1 = new listwidget(win) {
			move(39,49)
			resize(395,385)
			setstylesheet("color:black;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setcurrentItemChangedEvent("")
			setcurrentRowChangedEvent("")
			setcurrentTextChangedEvent("")
			setitemActivatedEvent("")
			setitemChangedEvent("")
			setitemClickedEvent("")
			setitemDoubleClickedEvent("")
			setitemEnteredEvent("")
			setitemPressedEvent("")
			setitemSelectionChangedEvent("")
			
		}
		Button1 = new pushbutton(win) {
			move(39,455)
			resize(180,35)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Add String")
			setClickEvent(Method(:test))
			setBtnImage(Button1,"")
			
		}
		Button2 = new pushbutton(win) {
			move(254,455)
			resize(180,35)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Add Many Numbers")
			setClickEvent(Method(:AddNumbers))
			setBtnImage(Button2,"")
			
		}
		LineEdit1 = new lineedit(win) {
			move(97,516)
			resize(213,42)
			setstylesheet("color:black;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent("")
			setselectionChangedEvent("")
			settextEditedEvent("")
			
		}
		Button3 = new pushbutton(win) {
			move(321,511)
			resize(113,49)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Add Text")
			setClickEvent(Method(:myAdd))
			setBtnImage(Button3,"")
			
		}
		Button4 = new pushbutton(win) {
			move(39,590)
			resize(396,40)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Show Second Window")
			setClickEvent(Method(:Second))
			setBtnImage(Button4,"")
			
		}
		Label1 = new label(win) {
			move(50,512)
			resize(38,43)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Text")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
	}

# End of the Generated Source Code File...