# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.15 Form Designer
# Date : 07/05/2021
# Time : 04:10:56

Load "stdlibcore.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new App {
		StyleFusion()
		new ToDoView { win.show() } 
		exec()
	}
}

class ToDoView from WindowsViewParent
	win = new MainWindow() { 
		move(20,20)
		resize(547,587)
		setWindowTitle("ToDo Application")
		setstylesheet("background-color:#c0ff6e;") 
		ListWidget1 = new listwidget(win) {
			move(83,30)
			resize(366,225)
			setstylesheet("color:black;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setcurrentItemChangedEvent("")
			setcurrentRowChangedEvent("")
			setcurrentTextChangedEvent("")
			setitemActivatedEvent("")
			setitemChangedEvent("")
			setitemClickedEvent("")
			setitemDoubleClickedEvent("")
			setitemEnteredEvent("")
			setitemPressedEvent("")
			setitemSelectionChangedEvent("")
			
		}
		Label1 = new label(win) {
			move(15,27)
			resize(46,37)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Tasks")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
		Label2 = new label(win) {
			move(18,263)
			resize(46,44)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Task")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
		LineEdit1 = new lineedit(win) {
			move(81,263)
			resize(366,44)
			setstylesheet("color:black;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent("")
			setselectionChangedEvent("")
			settextEditedEvent("")
			
		}
		Button1 = new pushbutton(win) {
			move(458,263)
			resize(59,44)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Add")
			setClickEvent(Method(:AddTask))
			setBtnImage(Button1,"")
			
		}
		Button6 = new pushbutton(win) {
			move(463,33)
			resize(59,44)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Delete")
			setClickEvent(Method(:DeleteTask))
			setBtnImage(Button6,"")
			
		}
		Button3 = new pushbutton(win) {
			move(81,319)
			resize(366,45)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Add Numbers")
			setClickEvent(Method(:Test))
			setBtnImage(Button3,"")
			
		}
		Button8 = new pushbutton(win) {
			move(81,374)
			resize(366,45)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Print Message")
			setClickEvent(Method(:Test2))
			setBtnImage(Button8,"")
			
		}
		Button5 = new pushbutton(win) {
			move(81,429)
			resize(366,54)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Change Color")
			setClickEvent(Method(:Test3))
			setBtnImage(Button5,"")
			
		}
		Button10 = new pushbutton(win) {
			move(81,488)
			resize(366,54)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Maximize the Window")
			setClickEvent(Method(:Test4))
			setBtnImage(Button10,"")
			
		}
	}

# End of the Generated Source Code File...