# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.15 Form Designer
# Date : 18/07/2021
# Time : 01:34:48

Load "stdlibcore.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new App {
		StyleFusion()
		new App1View { win.show() } 
		exec()
	}
}

class App1View from WindowsViewParent
	win = new MainWindow() { 
		move(20,20)
		resize(402,296)
		setWindowTitle("Form1")
		setstylesheet("background-color:;") 
		Button1 = new pushbutton(win) {
			move(312,26)
			resize(64,41)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Add")
			setClickEvent(Method(:sayhello))
			setBtnImage(Button1,"")
			
		}
		Label1 = new label(win) {
			move(19,26)
			resize(138,36)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Task")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
		LineEdit1 = new lineedit(win) {
			move(84,26)
			resize(207,41)
			setstylesheet("color:black;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent("")
			setselectionChangedEvent("")
			settextEditedEvent("")
			
		}
		ListWidget1 = new listwidget(win) {
			move(84,89)
			resize(207,156)
			setstylesheet("color:black;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setcurrentItemChangedEvent("")
			setcurrentRowChangedEvent("")
			setcurrentTextChangedEvent("")
			setitemActivatedEvent("")
			setitemChangedEvent("")
			setitemClickedEvent("")
			setitemDoubleClickedEvent("")
			setitemEnteredEvent("")
			setitemPressedEvent("")
			setitemSelectionChangedEvent("")
			
		}
		Label5 = new label(win) {
			move(18,89)
			resize(48,36)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Tasks")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
	}

# End of the Generated Source Code File...