# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.16 Form Designer
# Date : 12/10/2021
# Time : 13:02:30

Load "stdlibcore.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new App {
		StyleFusion()
		new app1View { win.show() } 
		exec()
	}
}

class app1View from WindowsViewParent
	win = new MainWindow() { 
		move(0,0)
		resize(983,572)
		setWindowTitle("Form1")
		setstylesheet("background-color:;") 
		Label1 = new label(win) {
			move(70,47)
			resize(158,47)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Label1")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
		Button1 = new pushbutton(win) {
			move(115,148)
			resize(148,56)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("test")
			setClickEvent(Method(:test))
			setBtnImage(Button1,"")
			
		}
		LineEdit1 = new lineedit(win) {
			move(196,44)
			resize(142,36)
			setstylesheet("color:black;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("")
			setTextChangedEvent("")
			setcursorPositionChangedEvent("")
			seteditingFinishedEvent("")
			setreturnPressedEvent("")
			setselectionChangedEvent("")
			settextEditedEvent("")
			
		}
		TextEdit1 = new textedit(win) {
			move(63,234)
			resize(213,102)
			setstylesheet("color:black;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("")
			setcopyAvailableEvent("")
			setcurrentCharFormatChangedEvent("")
			setcursorPositionChangedEvent("")
			setredoAvailableEvent("")
			setselectionChangedEvent("")
			settextChangedEvent("")
			setundoAvailableEvent("")
			
		}
		ListWidget1 = new listwidget(win) {
			move(293,109)
			resize(80,99)
			setstylesheet("color:black;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setcurrentItemChangedEvent("")
			setcurrentRowChangedEvent("")
			setcurrentTextChangedEvent("")
			setitemActivatedEvent("")
			setitemChangedEvent("")
			setitemClickedEvent("")
			setitemDoubleClickedEvent("")
			setitemEnteredEvent("")
			setitemPressedEvent("")
			setitemSelectionChangedEvent("")
			
		}
		CheckBox1 = new checkbox(win) {
			move(24,123)
			resize(70,17)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("CheckBox1")
			setstateChangedEvent("")
			setclickedEvent("")
			setpressedEvent("")
			setreleasedEvent("")
			settoggledEvent("")
			
		}
		Slider1 = new slider(win) {
			move(10,169)
			resize(100,50)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setOrientation(1)
			setactionTriggeredEvent("")
			setrangeChangedEvent("")
			setsliderMovedEvent("")
			setsliderPressedEvent("")
			setsliderReleasedEvent("")
			setvalueChangedEvent("")
			
		}
		Progressbar1 = new progressbar(win) {
			move(34,0)
			resize(119,35)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setOrientation(1)
			setvalueChangedEvent("")
			
		}
		Spinbox1 = new spinbox(win) {
			move(11,297)
			resize(40,47)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setvalueChangedEvent("")
			
		}
		Combobox1 = new combobox(win) {
			move(32,367)
			resize(216,48)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setactivatedEvent("")
			setcurrentIndexChangedEvent("")
			seteditTextChangedEvent("")
			sethighlightedEvent("")
			
		}
		Datetimeedit1 = new datetimeedit(win) {
			move(56,454)
			resize(141,49)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			
		}
		TableWidget1 = new tablewidget(win) {
			move(608,369)
			resize(271,113)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setColumnCount(2)
			setHorizontalHeaderItem(1, new QTableWidgetItem("One"))
			setHorizontalHeaderItem(2, new QTableWidgetItem("Two"))
			setColumnwidth(1,100)
			setColumnwidth(2,100)
			setSelectionBehavior(QAbstractItemView_SelectRows)
			setAlternatingRowColors(True)
			setcellActivatedEvent("")
			setcellChangedEvent("")
			setcellClickedEvent("")
			setcellDoubleClickedEvent("")
			setcellEnteredEvent("")
			setcellPressedEvent("")
			setcurrentCellChangedEvent("")
			setcurrentItemChangedEvent("")
			setitemActivatedEvent("")
			setitemChangedEvent("")
			setitemClickedEvent("")
			setitemDoubleClickedEvent("")
			setitemEnteredEvent("")
			setitemPressedEvent("")
			setitemSelectionChangedEvent("")
			
		}
		TreeWidget1 = new treewidget(win) {
			move(323,351)
			resize(275,142)
			setstylesheet("color:black;background-color:white;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setColumnCount(0)
			setHeaderHidden(True)
			setcollapsedEvent("")
			setexpandedEvent("")
			setactivatedEvent("")
			setclickedEvent("")
			setdoubleClickedEvent("")
			setenteredEvent("")
			setpressedEvent("")
			setviewportEnteredEvent("")
			setcurrentItemChangedEvent("")
			setitemActivatedEvent("")
			setitemChangedEvent("")
			setitemClickedEvent("")
			setitemCollapsedEvent("")
			setitemDoubleClickedEvent("")
			setitemEnteredEvent("")
			setitemExpandedEvent("")
			setitemPressedEvent("")
			setitemSelectionChangedEvent("")
			
		}
		RadioButton1 = new radiobutton(win) {
			move(286,297)
			resize(137,37)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("RadioButton1")
			setclickedEvent("")
			setpressedEvent("")
			setreleasedEvent("")
			settoggledEvent("")
			
		}
		WebView1 = new webview(win) {
			move(391,13)
			resize(558,325)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			loadpage(new qURL(""))
			setloadProgressEvent ("")
			setloadStartedEvent ("")
			setselectionChangedEvent ("")
			seturlChangedEvent ("")
			
		}
		Dial1 = new dial(win) {
			move(301,227)
			resize(70,61)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setvalueChangedEvent("")
			
		}
		VideoWidget1 = new videowidget(win) {
			move(200,439)
			resize(100,61)
			setstylesheet("color:black;background-color:#55ffff;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			playerVideoWidget1 = new qmediaplayer() { 
			setmedia(new qurl(""))
			 setvideooutput(VideoWidget1)
			}
			
		}
		Frame1 = new frame3(win) {
			move(148,103)
			resize(117,36)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setFrameStyle(QFrame_Plain | QFrame_WinPanel)
		}
		LCDNumber1 = new lcdnumber(win) {
			move(173,3)
			resize(166,38)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			Display(0)
			
		}
	}

# End of the Generated Source Code File...