# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.19 Form Designer
# Date : 20/10/2023
# Time : 16:38:05

Load "stdlibcore.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new App {
		StyleFusion()
		new testView { win.show() } 
		exec()
	}
}

class testView from WindowsViewParent
	win = new MainWindow() { 
		move(20,20)
		resize(635,461)
		setWindowTitle("Using Menubar")
		setstylesheet("background-color:;") 

		oMenuBar = new qmenubar(win) {
			subMenu1 = addmenu("File")
			subMenu1 {

				oAction1_1 = new qAction(win) {
					setShortcut(new QKeySequence(""))
					setbtnimage(self,"")
					settext("About")
					setclickevent(Method(:About))
				}
				addaction(oAction1_1)

				oAction1_2 = new qAction(win) {
					setShortcut(new QKeySequence(""))
					setbtnimage(self,"")
					settext("Exit")
					setclickevent(Method(:CloseApp))
				}
				addaction(oAction1_2)
			}
		}
		win.SetMenuBar(oMenuBar)
 
	}

# End of the Generated Source Code File...