# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.17 Form Designer
# Date : 20/04/2022
# Time : 23:58:59

Load "stdlibcore.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new App {
		StyleFusion()
		new App1View { win.show() } 
		exec()
	}
}

class App1View from WindowsViewParent
	win = new MainWindow() { 
		move(0,20)
		resize(335,454)
		setWindowTitle("Form1")
		setstylesheet("background-color:;") 
		Label1 = new label(win) {
			move(5,23)
			resize(301,48)
			setstylesheet("color:;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial,22,-1,5,50,0,0,0,0,0,Regular")
			setfont(oFont)
			oFont.delete()
			setText("Numbers And Squares")
			setAlignment(Qt_AlignLeft |  Qt_AlignVCenter)
		}
		TableWidget1 = new tablewidget(win) {
			move(5,79)
			resize(301,248)
			setstylesheet("color:;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setColumnCount(0)
			setSelectionBehavior(QAbstractItemView_SelectItems)
			setAlternatingRowColors(True)
			setcellActivatedEvent("")
			setcellChangedEvent("")
			setcellClickedEvent("")
			setcellDoubleClickedEvent("")
			setcellEnteredEvent("")
			setcellPressedEvent("")
			setcurrentCellChangedEvent("")
			setcurrentItemChangedEvent("")
			setitemActivatedEvent("")
			setitemChangedEvent("")
			setitemClickedEvent("")
			setitemDoubleClickedEvent("")
			setitemEnteredEvent("")
			setitemPressedEvent("")
			setitemSelectionChangedEvent("")
			
		}
		Button1 = new pushbutton(win) {
			move(5,346)
			resize(301,44)
			setstylesheet("color:;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("Save to CSV")
			setClickEvent(Method(:Save_to_CSV))
			setBtnImage(Button1,"")
			
		}
	}

# End of the Generated Source Code File...