# Form/Window View - Generated Source Code File 
# Generated by the Ring 1.8 Form Designer
# Date : 08/05/2018
# Time : 16:50:05

Load "stdlib.ring"
Load "guilib.ring"

import System.GUI

if IsMainSourceFile() { 
	new App {
		StyleFusion()
		new firstappView { win.show() } 
		exec()
	}
}

class firstappView from WindowsViewParent
	win = new MainWindow() { 
		move(10,145)
		resize(400,400)
		setWindowTitle("النافذة 1")
		setstylesheet("background-color:;") 
		Button1 = new pushbutton(win) {
			move(83,74)
			resize(280,54)
			setstylesheet("color:black;background-color:;")
			oFont = new qfont("",0,0,0)
			oFont.fromstring("Arial")
			setfont(oFont)
			oFont.delete()
			setText("السلام عليكم")
			setClickEvent(Method(:سلام))
			setBtnImage(Button1,"")
			
		}
	}

# End of the Generated Source Code File...